#!/usr/bin/env bash

if [[ "$1" == "" ]]; then
    echo Usage: rust-ctags [--vim] dirs...
    echo
    echo Generates a TAGS file with Rust contents from the given directories.
    echo
    echo Options:
    echo
    echo    --vim: Generates a VIM-style TAGS file. By default,
    echo           an emacs-style file is generated.
    exit 1
fi

if [[ "$1" == "--vim" ]]; then
    shift
    OPTIONS=""
else
    OPTIONS="-e"
fi

MYDIR=$(dirname $0)

if [ ! -f "$MYDIR/ctags.rust" ]; then
  echo ctags.rust definition not found, should be at path $MYDIR/ctags.rust
  exit 1
fi

rm -f TAGS

for SRCDIR in "$@"; do
    echo "Indexing $SRCDIR"

    if [ ! -d "$SRCDIR" ]; then
        echo Source directory "'"$SRCDIR"'" not found.
        exit 1
    fi

    ctags -a $OPTIONS -f TAGS --options="$MYDIR/ctags.rust" --languages=Rust --recurse "$SRCDIR"
done
